# Generated by Django 5.0.4 on 2024-04-28 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('company_username', models.CharField(max_length=150)),
                ('company_email', models.CharField(max_length=150)),
                ('company_create_password', models.CharField(max_length=8)),
                ('company_image', models.ImageField(blank=True, null=True, upload_to='img/%y')),
                ('company_description', models.TextField()),
                ('company_contact', models.BigIntegerField()),
                ('company_address', models.CharField(max_length=100)),
                ('company_bankname', models.CharField(max_length=100)),
                ('company_accountNo', models.BigIntegerField()),
                ('company_ifsc', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=150)),
                ('user_lname', models.CharField(max_length=150)),
                ('user_email', models.CharField(max_length=150)),
                ('user_create_password', models.CharField(max_length=8)),
                ('user_dob', models.DateField()),
                ('user_city', models.CharField(max_length=100)),
                ('user_state', models.CharField(max_length=100)),
                ('user_pincode', models.IntegerField()),
                ('user_contact', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='img/%y')),
                ('product_originalPrice', models.FloatField()),
                ('product_sellingPrice', models.FloatField()),
                ('product_color', models.CharField(max_length=100)),
                ('product_battery', models.CharField(max_length=100)),
                ('product_storage', models.CharField(max_length=100)),
                ('product_screen', models.CharField(max_length=100)),
                ('product_network', models.CharField(max_length=100)),
                ('product_features', models.TextField()),
                ('status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0-default,1-Trending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceapp.company')),
            ],
        ),
    ]
