# Generated by Django 5.0.4 on 2024-04-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_originalPrice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sellingPrice',
            field=models.IntegerField(),
        ),
    ]
