# Generated by Django 5.0.4 on 2024-04-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='odprocolor',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='odproprice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='odprostorage',
            field=models.CharField(max_length=150),
        ),
    ]
