# Generated by Django 5.0.2 on 2024-05-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0005_order_odcomname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='odcomname',
            field=models.CharField(default=False, max_length=150),
        ),
    ]
