# Generated by Django 5.0.2 on 2024-05-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0006_alter_order_odcomname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='odcomname',
            field=models.CharField(max_length=150),
        ),
    ]
