# Generated by Django 5.0.2 on 2024-05-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0007_alter_order_odcomname'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oduserfname',
            field=models.CharField(default=False, max_length=150),
        ),
    ]
